name: Build Windows 7 EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:   # позволяет запускать сборку вручную

jobs:
  build:
    runs-on: windows-latest # образ Windows, совместимый с Win7
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'   # версия, которая дружит с Windows 7
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller==4.10   # версия PyInstaller, стабильная на Win7
          pip install -r requirements.txt
          
      - name: Build EXE
        run: pyinstaller --onefile --windowed VKR(1).py
        # замените "ваш_скрипт.py" на имя вашего файла
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: stego-windows7-exe
          path: dist/
